config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources :posts do
    resources :comments, only: [:new, :create]
  end
  resources :comments
  devise_for :users
  resources :users
  get 'profile', to: 'users#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :posts_tags
    has_many :tags, through: :posts_tags
    has_many :comments

    validates :title, presence: true
    validates :content, presence: true
    validates :user_id, presence: true
    validates :answers_count, presence: true, numericality: { greater_than_or_equal_to: 0 }
    validate :set_published_at

    private
        def set_published_at
            self.published_at = Time.now unless published_at.present?
        end
end

app/models/posts_tag.rb
class PostsTag < ApplicationRecord
    belongs_to :post
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :posts_tags
    has_many :posts, through: :posts_tags

    validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :posts
  has_many :comments

    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
    
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:index, :show]
    
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected

    def after_sign_up_path_for(resource)
      root_path
    end

    def after_sign_in_path_for(resource)
      root_path
    end
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end


  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    if params[:post_id]
      post = Post.find_by(id: params[:post_id])
      @comment.post = post
    end
  end

  # GET /comments/1/edit
  def edit
    unless @comment.user_id == current_user.id
      redirect_to @comment, alert: "You don't have permission to edit this comment."
    end
  end

  # POST /comments or /comments.json
  def create
    @comment = current_user.comments.build(comment_params)
  
    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    if @comment.user_id == current_user.id
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
          format.json { render :show, status: :ok, location: @comment }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @comment, alert: "You don't have permission to edit this comment." }
        format.json { render json: { error: "Permission denied" }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    if @comment.user_id == current_user.id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to comments_url, alert: "You don't have permission to delete this comment." }
        format.json { render json: { error: "Permission denied" }, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :authorize_user!, only: [:edit, :update, :destroy]
  
	def index
	  @posts = Post.all
	end
  
	def show
	  # No es necesario encontrar el post aquí porque ya está configurado en el before_action
	end
  
	def new
	  @post = current_user.posts.build # Crea un nuevo post asociado al usuario actual
	end
  
	def create  
	  @post = current_user.posts.build(post_params) # Asigna el ID del usuario actual al post
	  if @post.save
		redirect_to posts_path, notice: 'Post was successfully created.'
	  else
		render :new
	  end
	end
  
	def edit
	  # No es necesario encontrar el post aquí porque ya está configurado en el before_action
	end
  
	def update
	  if @post.update(post_params)
		redirect_to posts_path, notice: 'Post was successfully updated.'
	  else
		render :edit
	  end
	end
  
	def destroy
	  @post.destroy
	  redirect_to posts_path, notice: 'Post was successfully destroyed.'
	end
  
	private
  
	def set_post
	  @post = Post.find(params[:id])
	end
  
	def authorize_user!
	  redirect_to root_path, alert: 'You are not authorized to perform this action.' unless @post.user == current_user
	end
  
	def post_params
	  params.require(:post).permit(:title, :content, :user_id, :answers_count)
	end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    def profile
      @user = current_user
      @posts = @user.posts
      @comments = @user.comments
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/perfiles_helper.rb
module PerfilesHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <div class="form-group mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", required: true %>
  </div>

  <% if comment.new_record? %>
    <% if params[:post_id] %>
      <%= form.hidden_field :post_id, value: params[:post_id] %>
    <% else %>
      <div class="form-group mb-3">
        <%= form.label :post_id %>
        <%= form.collection_select :post_id, Post.all, :id, :title, {prompt: "Select a post"}, {class: "form-control"} %>
      </div>
    <% end %>
  <% else %>
    <div class="form-group mb-3">
      <%= form.label :post_id %>
      <%= form.collection_select :post_id, Post.all, :id, :title, {prompt: "Select a post"}, {class: "form-control", disabled: true} %>

    </div>
  <% end %>

  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<%= link_to 'New Comment', new_comment_path, class: 'btn btn-primary' %>


<table class="table">
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Post</th>
      <th> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><a href="/users/<%= comment.user_id %>"><%= comment.user_id %></a></td>
        <td><a href="/posts/<%= comment.post_id %>"><%= comment.post_id %></a></td>
        <td>
          <%= link_to 'Show', comment, class: 'btn btn-info' %>
          <%= link_to 'Edit', edit_comment_path(comment), class: 'btn btn-warning' %>
          <%= button_to 'Destroy', comment, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger' %>
            
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

app/views/comments/show.html.erb
<h1>Showing comment</h1>

<p><strong>Body:</strong></p>
<p><%= @comment.body %></p>

<p><strong>User:</strong></p>
<p><a href="/users/<%= @comment.user_id %>"><%= @comment.user_id %></a></p>

<p><strong>Post:</strong></p>
<p><a href="/posts/<%= @comment.post_id %>"><%= @comment.post_id %></a></p>

<div>

  <%= link_to "Edit this comment", edit_comment_path(@comment), class: "btn btn-warning" %>
  <%= link_to "Back to comments", comments_path, class: "btn btn-primary" %>
  <%= button_to "Destroy this comment", @comment, data: { turbo_confirm: 'Are you sure?', turbo_method: "delete" }, class: "btn btn-danger", method: :delete %>
  
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Y</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/posts">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/comments">Comment</a>
        </li>
      </ul>
      <% if user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Profile", profile_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link btn btn-link" %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <div class="form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control", required: true %>
  </div>

  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<div class="col-3">  
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= post.user.name %></h6>
      <p class="card-text"><%= post.content.truncate 50 %></p>
      <p class="card-text">Comments: <%= post.comments.count %></p>
      <%= link_to 'View', post, class: 'card-link btn btn-primary' %>
      <%= link_to 'Edit', edit_post_path(post), class: 'card-link btn btn-warning' %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= link_to 'New Post', new_post_path, class: 'btn btn-primary mb-2' %>
<div class="row">
  <%= render partial: 'post', collection: @posts %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2>Author: <%= @post.user.name %></h2>
<p><%= @post.content %></p>
<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning' %>
<%= link_to 'Back', posts_path, class: 'btn btn-primary' %>
<%= link_to 'New Comment', new_post_comment_path(@post), class: 'btn btn-primary' %>
<%= button_to 'Destroy', @post, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger' %>

<h2>Comments</h2>

<table class="table">
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post.comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user.name %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= button_to 'Destroy', @comment, data: { confirm: 'Are you sure?' }, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/profile.html.erb
<h1>Profile</h1>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<h2>Posts</h2>
<% if @posts.any? %>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <strong><%= link_to post.title, post_path(post) %></strong><br>
        <%= truncate(post.content, length: 100) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No posts found.</p>
<% end %>

<h2>Comments</h2>
<% if @comments.any? %>
  <ul>
    <% @comments.each do |comment| %>
      <li>
        <strong>On Post:</strong> <%= link_to comment.post.title, post_path(comment.post) %><br>
        <%= comment.body %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No comments found.</p>
<% end %>

<%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-warning' %>
<%= link_to 'Back to Home', root_path, class: 'btn btn-primary' %>